name: Development

on:
  push:
    branches: [develop, feature/*]
  pull_request:
    branches: [develop]

jobs:
  quick-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Quick lint check
        run: npm run lint:check
        
      - name: Quick format check
        run: npm run format:check
        
      - name: Type checking
        run: npm run typecheck

  build-test:
    runs-on: ubuntu-latest
    needs: quick-check
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build development version
        run: npm run build:dev
        
      - name: Upload development build
        uses: actions/upload-artifact@v4
        with:
          name: dev-build
          path: |
            plugin/
            public/js/
          retention-days: 3